In [ ]:
#Two bar truss having one external load at node2
# Two end are fixed supports

In [13]:
import numpy as np
import calfem.core as cfc

In [10]:
#Topology matrix Edof
Edof = np.array([
    [1,2,3,4],
    [3,4,5,6]
])
Edof

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [16]:
#Stiffness matrix K and load vector f
K = np.matrix(np.zeros((6,6)))
f = np.matrix(np.zeros((6,1)))
K
f


matrix([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [4]:
#Element properties
E = 2e5
A1 = 200
A2 = 200
L1 = 500
L2 = 500
ep1 = [E,A1]
ep2 = [E,A2]


In [5]:
#Element coordinates
ex1 = np.array([500, 900])
ex2 = np.array([0.0, 500])

ey1 = np.array([0.0, -300])
ey2 = np.array([0.0, 0.0])


In [6]:
#Element stiffness matrices
Ke1 = cfc.bar2e(ex1,ey1,ep1)
Ke2 = cfc.bar2e(ex2,ey2,ep2)
print(Ke1)
print(Ke2)


[[ 51200. -38400. -51200.  38400.]
 [-38400.  28800.  38400. -28800.]
 [-51200.  38400.  51200. -38400.]
 [ 38400. -28800. -38400.  28800.]]
[[ 80000.      0. -80000.      0.]
 [     0.      0.      0.      0.]
 [-80000.      0.  80000.      0.]
 [     0.      0.      0.      0.]]


In [7]:
#Assemble Ke into K
cfc.assem(Edof[0,:],K,Ke1)
cfc.assem(Edof[1,:],K,Ke2)

print("Stiffness matrix K:k1+k2")
print(K)


Stiffness matrix K:k1+k2
[[ 51200. -38400. -51200.  38400.      0.      0.]
 [-38400.  28800.  38400. -28800.      0.      0.]
 [-51200.  38400. 131200. -38400. -80000.      0.]
 [ 38400. -28800. -38400.  28800.      0.      0.]
 [     0.      0. -80000.      0.  80000.      0.]
 [     0.      0.      0.      0.      0.      0.]]


In [8]:
#Solve the system of equations
bc = np.array([1,2,5,6])
f[3] = -12000
U, r = cfc.solveq(K,f,bc)

print("\nDisplacements U:")
print(U)

print("\nReaction forces r:")
print(r)



Displacements U:
[[ 0.        ]
 [ 0.        ]
 [-0.2       ]
 [-0.68333333]
 [ 0.        ]
 [ 0.        ]]

Reaction forces r:
[[-16000.]
 [ 12000.]
 [     0.]
 [     0.]
 [ 16000.]
 [     0.]]
